import pygame
import time
from threading import Thread
pygame.mixer.init()
pygame.mixer.music.load("/Users/quocvietphan/Desktop/Tools/Helikopter.wav")
pygame.mixer.music.play()
while True:
    print("                                                                                  ")
    print("                                                                                  ")
    print("                                                                                  ")
    print("                                                                                  ")
    print("                                                                                  ")
    print("                                                                                  ")
    print("                                                   LOL                            ")
    print("                           |ROFL||ROFL||ROFL||ROFL|LOL|ROFL||ROFL||ROFL||ROFL|    ")
    print("                                                   LOL                            ")
    print("                  /|                               LOL                            ")
    print("                 /||                    //===============||=======\\              ")
    print("                /LOL|                  //                ||        \\             ")
    print("          -----||LOL||-----------------||                ||         ||            ")
    print("          -----||LOL||-----------------||                ===========||            ")
    print("                |LOL/                  \\                           //            ")
    print("                 ||/                    \\=========================//             ")
    print("                 |/                             ||         ||                     ")
    print("                                         _______||_________||________/            ")
    print("                                                                                  ")
    print("                                                                                  ")
    print("                                                                                  ")
    print("                                                                                  ")
    print("                                                                                  ")
    print("                                                                                  ")
    time.sleep(0.05)
    print("                                                                                  ")
    print("                                                                                  ")
    print("                                                                                  ")
    print("                                                                                  ")
    print("                                                                                  ")
    print("                                                                                  ")
    print("                                                   LOL                            ")
    print("                                                   LOL|ROFL||ROFL||ROFL||ROFL|    ")
    print("                                                   LOL                            ")
    print("                                                   LOL                            ")
    print("                                        //===============||=======\\              ")
    print("                                       //                ||        \\             ")
    print("          -----||LOL||-----------------||                ||         ||            ")
    print("          -----||LOL||-----------------||                ===========||            ")
    print("                |LOL/                  \\                           //            ")
    print("                 ||/                    \\=========================//             ")
    print("                 |/                             ||         ||                     ")
    print("                                         _______||_________||________/            ")
    print("                                                                                  ")
    print("                                                                                  ")
    print("                                                                                  ")
    print("                                                                                  ")
    print("                                                                                  ")
    print("                                                                                  ")
    time.sleep(0.05)
    print("                                                                                  ")
    print("                                                                                  ")
    print("                                                                                  ")
    print("                                                                                  ")
    print("                                                                                  ")
    print("                                                                                  ")
    print("                                                   LOL                            ")
    print("                           |ROFL||ROFL||ROFL||ROFL|LOL                            ")
    print("                                                   LOL                            ")
    print("                  /|                               LOL                            ")
    print("                 /||                    //===============||=======\\              ")
    print("                /LOL|                  //                ||        \\             ")
    print("          -----||LOL||-----------------||                ||         ||            ")
    print("          -----||LOL||-----------------||                ===========||            ")
    print("                                       \\                           //            ")
    print("                                        \\=========================//             ")
    print("                                                ||         ||                     ")
    print("                                         _______||_________||________/            ")
    print("                                                                                  ")
    print("                                                                                  ")
    print("                                                                                  ")
    print("                                                                                  ")
    print("                                                                                  ")
    print("                                                                                  ")
    time.sleep(0.05)